
redis.server.host: "redis-server"
redis.server.port: "6379"
cache.service.url: "http://cacheservice:8003"

cacheService.host: "locahlhost"
cacheService.port: "8003"

bookService.host: "localhost"
bookService.port: "8004"
