# ===============================
# = DataSource Configuration =
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MealMeat?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # options: none, validate, update, create, create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# ===============================
# = DataSource Configuration =
# ===============================
redis.server.host: "redis-server"
redis.server.port: "6379"
cache.service.url: "http://cacheservice:8003"

cacheService.host: "locahlhost"
cacheService.port: "8003"

bookService.host: "localhost"
bookService.port: "8004"
