spring:
  datasource:
    url: jdbc:mysql://http://127.0.0.1:3306/BookStore
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    

redis.server.host: "redis-server"
redis.server.port: "6379"
cacheService.host: "172.18.0.2"
cacheService.port: "8003"
cache.service.url: "http://cacheservice:8003"
bookService.host: "172.18.0.2"
bookService.port: "8004"
